#inherit_from: .rubocop_todo.yml
require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'log/*'
    - 'node_modules/**/*'
    - 'config/application.rb'
    - 'db/**/*'
    - 'lib/tasks/**/*'

  TargetRubyVersion: 2.7.2

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/admin/**/*'
    - 'config/routes.rb'
    - 'config/routes/**/*'

RSpec/NamedSubject:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/AsciiComments:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table

Lint/MissingSuper:
  Enabled: false
